version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - monitoring
    volumes:
      - prometheus:/prometheus
      - ./prometheus/:/etc/prometheus/

  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    depends_on:
      - prometheus
    ports:
      - :3000
    networks:
      - monitoring
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  node-exporter-1:
    container_name: node-exporter-1
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    # ports:
    #   - 9101:9100
    networks:
      - monitoring
    deploy:
      mode: global

  node-exporter-2:
    container_name: node-exporter-2
    image: prom/node-exporter:${NODE_EXPORTER_VERSION}
    # ports:
    #   - 9102:9100
    networks:
      - monitoring
    deploy:
      mode: global

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:${ALERTMANAGER_VERSION}
    depends_on:
      - prometheus
    ports:
      - 9093:9093
    networks:
      - monitoring
    volumes:
      - ./alertmanager/:/etc/alertmanager/

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus:
  grafana:
