version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROMETHEUS_VERSION}
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-remote-write-receiver
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus

  loki:
    container_name: loki
    image: grafana/loki:${LOKI_VERSION}
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/config.yml
    volumes:
      - loki-data:/loki
      - ./loki:/etc/loki

  promtail:
    container_name: promtail
    image: grafana/promtail:${PROMTAIL_VERSION}
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail:/etc/promtail
      - ./logs/iis:/var/log/iis

  # node-exporter-1:
  #   container_name: node-exporter-1
  #   image: prom/node-exporter:${NODE_EXPORTER_VERSION}
  #   # ports:
  #   #   - 9101:9100
  #   deploy:
  #     mode: global
  #
  # node-exporter-2:
  #   container_name: node-exporter-2
  #   image: prom/node-exporter:${NODE_EXPORTER_VERSION}
  #   # ports:
  #   #   - 9102:9100
  #   deploy:
  #     mode: global
  #
  # alertmanager:
  #   container_name: alertmanager
  #   image: prom/alertmanager:${ALERTMANAGER_VERSION}
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
