{
 "title": "Grafana Loki Dashboard for IIS",
 "description": "Loki v2+ showcase using IIS logs",
 "time": { "from": "2023-02-28T10:45:00.000Z", "to": "2023-02-28T11:15:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "label_name", "label": "Label Name", "query": "label_names()" },
   { "name": "label_value", "label": "Label Value", "query": "label_values($label_name)" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({$label_name=~\"$label_value\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({$label_name=~\"$label_value\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "KPI's",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Realtime visitors ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(\n    sum by (c_ip) (\n        count_over_time(\n            { $label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\" } \n            # | regexp `^(?P<timestamp>[\\d-]+ [\\d:]+) (?P<s_ip>\\d+\\.\\d+\\.\\d+\\.\\d+) .+? (?P<c_ip>\\d+\\.\\d+\\.\\d+\\.\\d+)`\n            | pattern `<_> <_> <_> <_> <_> <_> <_> <_> <c_ip> <_> <_> <_> <_> <_> <_>`\n            | c_ip =~ `\\d+\\.\\d+\\.\\d+\\.\\d+`\n            # | __error__ = \"\" \n            [$__interval]\n        )\n    )\n)"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count (\n    sum by(s_ip) (\n        count_over_time(\n            {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"}\n            | regexp `^[\\d-]+ [\\d:]+ (?P<s_ip>[\\d\\.:]+)`\n            [$__interval]\n        )\n    )\n)"
    }
   ]
  },
  {
   "title": "% of 2xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n        | regexp `(?P<sc_status>\\d+) \\d+ \\d+ \\d+(\\r)?$` \n        | sc_status >= 200 and sc_status < 300 \n        | __error__ = \"\" \n        [$__interval]\n    )\n) / sum(\n    count_over_time(\n        {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n        [$__interval]\n    )\n) * 100"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n        | regexp `(?P<sc_status>\\d+) \\d+ \\d+ \\d+(\\r)?$` \n        | sc_status >= 500 \n        | __error__ = \"\" \n        [$__interval]\n    )\n) / sum(\n    count_over_time(\n        {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n        [$__interval]\n    )\n) * 100"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(\n    0.95, {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n    | regexp `(?P<time_taken>\\d+)(\\r)?$` \n    | label_format time_taken = \"{{.time_taken}}ms\"\n    | unwrap duration(time_taken)\n    | __error__ = \"\" \n    [$__interval] \n) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Status code over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (sc_status) (\n    count_over_time(\n        { $label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\" } \n        | regexp `.*? (?P<sc_status>\\d+) \\d+ \\d+ \\d+(\\r)?$` \n        | __error__=\"\" \n        [$__interval]\n    )\n)",
     "legendFormat": "{{by (sc_status)}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n| pattern `<_> <_> <_> <cs_method> <cs_uri> <_> <_> <_> <_> <_> <_> <sc_status> <_> <_> <time_taken>` \n| line_format \"➡️ {{.cs_method}} {{.cs_uri}} with HTTP status: {{.sc_status}} ({{.time_taken}}ms)\""
    }
   ]
  },
  {
   "title": "Top 10 Requested Pages",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, sum by (cs_uri) (\n    count_over_time(\n        # {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` \n        { $label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\" }\n        | pattern `<_> <_> <_> <_> <cs_uri> <_> <_> <_> <_> <_> <_> <sc_status> <_> <_> <_>` \n        | sc_status = 200 and cs_uri != \"/\" \n        | __error__ = \"\" \n        [$__interval]\n    )\n))",
     "legendFormat": "{{cs_uri}}"
    }
   ]
  },
  {
   "title": "Top 10 visitor IPs",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum by (c_ip) (\n    count_over_time(\n        {$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} \n        | pattern `<_> <_> <_> <_> <_> <_> <_> <_> <c_ip> <_> <_> <_> <_> <_> <_>` \n        |  __error__ = \"\"\n        [$__interval]\n    )\n))",
     "legendFormat": "{{c_ip}}"
    }
   ]
  },
  {
   "title": "Request statistics over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Acquisition and Behaviour",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 10 HTTP Referers",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_referer) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [15m])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  },
  {
   "title": "Top 10 User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 29 },
   "targets": [
    {
     "expr": "topk(10, sum by (http_user_agent) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | json |  __error__=\"\" [15m])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  }
 ]
}